name: learn_flutter_hooks
description: Hooksの学習

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  state_notifier:
  flutter_hooks:
  hooks_riverpod:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  pedantic_mono: any

flutter:

  uses-material-design: true
